[package]
name = "jfn-mediastation"
version.workspace = true
edition.workspace = true
publish.workspace = true

[lib]
name = "jfn_mediastation"
crate-type = ["rlib"]

[dependencies]
parking_lot.workspace = true
serde_json.workspace = true
sha2.workspace = true
ureq.workspace = true
url.workspace = true

[lints]
workspace = true
