//! Auto-generated libmpv FFI bindings.
//!
//! Generated by `build.rs` from `mpv/client.h` (system pkg-config or
//! `third_party/mpv/include` vendored fallback). See `build.rs` for the
//! allowlist and configuration.

#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
#![allow(non_upper_case_globals)]
#![allow(dead_code)]
#![allow(clippy::all)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

// Hand-written replacements for types bindgen 0.71 emits as opaque stubs
// (see build.rs). Layout matches `third_party/mpv/include/mpv/client.h`
// lines 803-845.

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mpv_node_list {
    pub num: ::std::os::raw::c_int,
    pub values: *mut mpv_node,
    pub keys: *mut *mut ::std::os::raw::c_char,
}

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mpv_byte_array {
    pub data: *mut ::std::os::raw::c_void,
    pub size: usize,
}

// stream_cb.h bindings (not generated by build.rs, which only includes
// client.h). Mirrors third_party/mpv/include/mpv/stream_cb.h.

pub type mpv_stream_cb_read_fn = unsafe extern "C" fn(
    cookie: *mut ::std::os::raw::c_void,
    buf: *mut ::std::os::raw::c_char,
    nbytes: u64,
) -> i64;
pub type mpv_stream_cb_seek_fn =
    unsafe extern "C" fn(cookie: *mut ::std::os::raw::c_void, offset: i64) -> i64;
pub type mpv_stream_cb_size_fn = unsafe extern "C" fn(cookie: *mut ::std::os::raw::c_void) -> i64;
pub type mpv_stream_cb_close_fn = unsafe extern "C" fn(cookie: *mut ::std::os::raw::c_void);
pub type mpv_stream_cb_cancel_fn = unsafe extern "C" fn(cookie: *mut ::std::os::raw::c_void);

#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct mpv_stream_cb_info {
    pub cookie: *mut ::std::os::raw::c_void,
    pub read_fn: Option<mpv_stream_cb_read_fn>,
    pub seek_fn: Option<mpv_stream_cb_seek_fn>,
    pub size_fn: Option<mpv_stream_cb_size_fn>,
    pub close_fn: Option<mpv_stream_cb_close_fn>,
    pub cancel_fn: Option<mpv_stream_cb_cancel_fn>,
}

pub type mpv_stream_cb_open_ro_fn = unsafe extern "C" fn(
    user_data: *mut ::std::os::raw::c_void,
    uri: *mut ::std::os::raw::c_char,
    info: *mut mpv_stream_cb_info,
) -> ::std::os::raw::c_int;

unsafe extern "C" {
    pub fn mpv_stream_cb_add_ro(
        ctx: *mut mpv_handle,
        protocol: *const ::std::os::raw::c_char,
        user_data: *mut ::std::os::raw::c_void,
        open_fn: Option<mpv_stream_cb_open_ro_fn>,
    ) -> ::std::os::raw::c_int;
}
